# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Lyrics
subtitle: ''
description: "Hi, I'm a backend developer. My interests lie broadly in technology, music, movies, and ACG. [Here](https://lyrics-reading.notion.site/43daf81093d84d9aa06306ad4c0e3254?v=698d707946014dd6a0390bc083335a1a) is a curated reading list maintained by myself."
keywords:
author: Lyrics
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: cactus

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  quotes: '“”‘’'
  modifyAnchors: 1
  anchorAlias: false
  autolink: true
  mangle: true
  sanitizeUrl: false
  dompurify: false
  headerIds: true
  lazyload: false
  figcaption: false
  prependRoot: true
  postAsset: false
  external_link:
    enable: false
    exclude: []
    nofollow: false
  disableNunjucks: false
  descriptionLists: true

# overwrite default config
theme_config:
  colorscheme: white
  # navigation menu
  nav:
    home: /
    about: /about/
    articles: /archives/
    projects: https://github.com/Aden-Q
    tag: /tags/
    category: /categories/
    search: /search/

  # show only the 5 most recent posts
  posts_overview:
    show_all_posts: false
    post_count: 5
    sort_updated: false

  # show links to social media accounts
  social_links:
  -
    icon: github
    link: https://github.com/Aden-Q
  -
    icon: mastodon
    link: https://mastodon.social/@zecheng
  -
    icon: mail
    link: mailto:qian0102@umn.edu

  # Enable MathJax support for Latex
  mathjax:
    enabled: true

  # Fill in your Disqus Comments Shortname to enable Disqus comments.
  disqus:
    enabled: true
    shortname: lyrics-zc

  highlight: atelier-forest-dark

  # Customize the copyright years
  # Note: if start_year/end_year not provided, will use current year.
  copyright:
    start_year: 2023
    end_year:

  rss:
    enable: true
    path: atom.xml
    limit: 20
    hub:
    content:
    content_limit: 140
    content_limit_delim: ' '
    order_by: -date
